define([], function(){

  var SVG_NAMESPACE = 'http://www.w3.org/2000/svg';
  var HEX_WIDTH = 150;
  var HEX_HEIGHT = Math.sqrt(3)/2 * HEX_WIDTH | 0;

  var COMBINATION_LOCK_SEGMENTS = 10;
  var COMBINATION_LOCK_SEGMENTS_SPACING = 5; // in degrees

  var ENUMS = {
    MODE: {
      LOCKED: 0
    },
    LOCK_STATE: {
      NONE: 0,
      TOUCH_POINTS: 1,
      DIALOG: 2
    }
  }

  return {
    SVG_NAMESPACE: SVG_NAMESPACE,
    HEX_WIDTH: HEX_WIDTH,
    HEX_HEIGHT: HEX_HEIGHT,
    COMBINATION_LOCK_SEGMENTS: COMBINATION_LOCK_SEGMENTS,
    COMBINATION_LOCK_SEGMENTS_SPACING: COMBINATION_LOCK_SEGMENTS_SPACING,
    ENUMS: ENUMS,
  }

});
